create table public.recipes (
  id bigint generated by default as identity primary key,
  title text not null,
  ingredients text,
  directions text,
  link text,
  source text,
  "NER" text
);

create index recipes_title_search_idx on public.recipes using gin (to_tsvector('english', coalesce(title, '')));
create index recipes_ingredients_search_idx on public.recipes using gin (to_tsvector('english', coalesce(ingredients, '') || ' ' || coalesce("NER", '')));

alter table public.recipes enable row level security;